// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cloudflare/cloudflare-go/v7/user"
	"github.com/cloudflare/cloudflare-go/v7/zones"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPI creates a new instance of MockAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPI {
	mock := &MockAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

type MockAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPI) EXPECT() *MockAPI_Expecter {
	return &MockAPI_Expecter{mock: &_m.Mock}
}

// CreateAPIToken provides a mock function for the type MockAPI
func (_mock *MockAPI) CreateAPIToken(ctx context.Context, params user.TokenNewParams) (*user.TokenNewResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIToken")
	}

	var r0 *user.TokenNewResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.TokenNewParams) (*user.TokenNewResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.TokenNewParams) *user.TokenNewResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.TokenNewResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.TokenNewParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_CreateAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIToken'
type MockAPI_CreateAPIToken_Call struct {
	*mock.Call
}

// CreateAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.TokenNewParams
func (_e *MockAPI_Expecter) CreateAPIToken(ctx any, params any) *MockAPI_CreateAPIToken_Call {
	return &MockAPI_CreateAPIToken_Call{Call: _e.mock.On("CreateAPIToken", ctx, params)}
}

func (_c *MockAPI_CreateAPIToken_Call) Run(run func(ctx context.Context, params user.TokenNewParams)) *MockAPI_CreateAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.TokenNewParams
		if args[1] != nil {
			arg1 = args[1].(user.TokenNewParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_CreateAPIToken_Call) Return(tokenNewResponse *user.TokenNewResponse, err error) *MockAPI_CreateAPIToken_Call {
	_c.Call.Return(tokenNewResponse, err)
	return _c
}

func (_c *MockAPI_CreateAPIToken_Call) RunAndReturn(run func(ctx context.Context, params user.TokenNewParams) (*user.TokenNewResponse, error)) *MockAPI_CreateAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function for the type MockAPI
func (_mock *MockAPI) GetToken(ctx context.Context, tokenID string) (*user.Token, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *user.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.Token, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.Token); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockAPI_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockAPI_Expecter) GetToken(ctx any, tokenID any) *MockAPI_GetToken_Call {
	return &MockAPI_GetToken_Call{Call: _e.mock.On("GetToken", ctx, tokenID)}
}

func (_c *MockAPI_GetToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockAPI_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_GetToken_Call) Return(v *user.Token, err error) *MockAPI_GetToken_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAPI_GetToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string) (*user.Token, error)) *MockAPI_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListTokens provides a mock function for the type MockAPI
func (_mock *MockAPI) ListTokens(ctx context.Context) ([]user.Token, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTokens")
	}

	var r0 []user.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]user.Token, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []user.Token); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_ListTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTokens'
type MockAPI_ListTokens_Call struct {
	*mock.Call
}

// ListTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAPI_Expecter) ListTokens(ctx any) *MockAPI_ListTokens_Call {
	return &MockAPI_ListTokens_Call{Call: _e.mock.On("ListTokens", ctx)}
}

func (_c *MockAPI_ListTokens_Call) Run(run func(ctx context.Context)) *MockAPI_ListTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPI_ListTokens_Call) Return(vs []user.Token, err error) *MockAPI_ListTokens_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockAPI_ListTokens_Call) RunAndReturn(run func(ctx context.Context) ([]user.Token, error)) *MockAPI_ListTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ListZones provides a mock function for the type MockAPI
func (_mock *MockAPI) ListZones(ctx context.Context, params zones.ZoneListParams) ([]zones.Zone, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListZones")
	}

	var r0 []zones.Zone
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, zones.ZoneListParams) ([]zones.Zone, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, zones.ZoneListParams) []zones.Zone); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]zones.Zone)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, zones.ZoneListParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPI_ListZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListZones'
type MockAPI_ListZones_Call struct {
	*mock.Call
}

// ListZones is a helper method to define mock.On call
//   - ctx context.Context
//   - params zones.ZoneListParams
func (_e *MockAPI_Expecter) ListZones(ctx any, params any) *MockAPI_ListZones_Call {
	return &MockAPI_ListZones_Call{Call: _e.mock.On("ListZones", ctx, params)}
}

func (_c *MockAPI_ListZones_Call) Run(run func(ctx context.Context, params zones.ZoneListParams)) *MockAPI_ListZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 zones.ZoneListParams
		if args[1] != nil {
			arg1 = args[1].(zones.ZoneListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_ListZones_Call) Return(zones1 []zones.Zone, err error) *MockAPI_ListZones_Call {
	_c.Call.Return(zones1, err)
	return _c
}

func (_c *MockAPI_ListZones_Call) RunAndReturn(run func(ctx context.Context, params zones.ZoneListParams) ([]zones.Zone, error)) *MockAPI_ListZones_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockAPI
func (_mock *MockAPI) RevokeToken(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockAPI_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockAPI_Expecter) RevokeToken(ctx any, tokenID any) *MockAPI_RevokeToken_Call {
	return &MockAPI_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, tokenID)}
}

func (_c *MockAPI_RevokeToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockAPI_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_RevokeToken_Call) Return(err error) *MockAPI_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *MockAPI_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCredentials provides a mock function for the type MockAPI
func (_mock *MockAPI) ValidateCredentials(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCredentials")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_ValidateCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCredentials'
type MockAPI_ValidateCredentials_Call struct {
	*mock.Call
}

// ValidateCredentials is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAPI_Expecter) ValidateCredentials(ctx any) *MockAPI_ValidateCredentials_Call {
	return &MockAPI_ValidateCredentials_Call{Call: _e.mock.On("ValidateCredentials", ctx)}
}

func (_c *MockAPI_ValidateCredentials_Call) Run(run func(ctx context.Context)) *MockAPI_ValidateCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPI_ValidateCredentials_Call) Return(err error) *MockAPI_ValidateCredentials_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_ValidateCredentials_Call) RunAndReturn(run func(ctx context.Context) error) *MockAPI_ValidateCredentials_Call {
	_c.Call.Return(run)
	return _c
}
