version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.24.3@sha256:5f7cdf218958c02c0da1356a3a2a8d1394c80206322d0790b968443f6875a59e
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml -- -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f coverage.txt
      - store_test_results:
          path: /tmp/test-reports

workflows:
  build-test:
    jobs:
      - build
