// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cloudflare/cloudflare-go/v7/packages/pagination"
	"github.com/cloudflare/cloudflare-go/v7/user"
	"github.com/cloudflare/cloudflare-go/v7/zones"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIInterface creates a new instance of MockAPIInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIInterface {
	mock := &MockAPIInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIInterface is an autogenerated mock type for the APIInterface type
type MockAPIInterface struct {
	mock.Mock
}

type MockAPIInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIInterface) EXPECT() *MockAPIInterface_Expecter {
	return &MockAPIInterface_Expecter{mock: &_m.Mock}
}

// CreateAPIToken provides a mock function for the type MockAPIInterface
func (_mock *MockAPIInterface) CreateAPIToken(ctx context.Context, params user.TokenNewParams) (*user.TokenNewResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIToken")
	}

	var r0 *user.TokenNewResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.TokenNewParams) (*user.TokenNewResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.TokenNewParams) *user.TokenNewResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.TokenNewResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.TokenNewParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIInterface_CreateAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIToken'
type MockAPIInterface_CreateAPIToken_Call struct {
	*mock.Call
}

// CreateAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.TokenNewParams
func (_e *MockAPIInterface_Expecter) CreateAPIToken(ctx interface{}, params interface{}) *MockAPIInterface_CreateAPIToken_Call {
	return &MockAPIInterface_CreateAPIToken_Call{Call: _e.mock.On("CreateAPIToken", ctx, params)}
}

func (_c *MockAPIInterface_CreateAPIToken_Call) Run(run func(ctx context.Context, params user.TokenNewParams)) *MockAPIInterface_CreateAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.TokenNewParams
		if args[1] != nil {
			arg1 = args[1].(user.TokenNewParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIInterface_CreateAPIToken_Call) Return(tokenNewResponse *user.TokenNewResponse, err error) *MockAPIInterface_CreateAPIToken_Call {
	_c.Call.Return(tokenNewResponse, err)
	return _c
}

func (_c *MockAPIInterface_CreateAPIToken_Call) RunAndReturn(run func(ctx context.Context, params user.TokenNewParams) (*user.TokenNewResponse, error)) *MockAPIInterface_CreateAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListZones provides a mock function for the type MockAPIInterface
func (_mock *MockAPIInterface) ListZones(ctx context.Context, params zones.ZoneListParams) (*pagination.V4PagePaginationArray[zones.Zone], error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListZones")
	}

	var r0 *pagination.V4PagePaginationArray[zones.Zone]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, zones.ZoneListParams) (*pagination.V4PagePaginationArray[zones.Zone], error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, zones.ZoneListParams) *pagination.V4PagePaginationArray[zones.Zone]); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.V4PagePaginationArray[zones.Zone])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, zones.ZoneListParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIInterface_ListZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListZones'
type MockAPIInterface_ListZones_Call struct {
	*mock.Call
}

// ListZones is a helper method to define mock.On call
//   - ctx context.Context
//   - params zones.ZoneListParams
func (_e *MockAPIInterface_Expecter) ListZones(ctx interface{}, params interface{}) *MockAPIInterface_ListZones_Call {
	return &MockAPIInterface_ListZones_Call{Call: _e.mock.On("ListZones", ctx, params)}
}

func (_c *MockAPIInterface_ListZones_Call) Run(run func(ctx context.Context, params zones.ZoneListParams)) *MockAPIInterface_ListZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 zones.ZoneListParams
		if args[1] != nil {
			arg1 = args[1].(zones.ZoneListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIInterface_ListZones_Call) Return(v4PagePaginationArray *pagination.V4PagePaginationArray[zones.Zone], err error) *MockAPIInterface_ListZones_Call {
	_c.Call.Return(v4PagePaginationArray, err)
	return _c
}

func (_c *MockAPIInterface_ListZones_Call) RunAndReturn(run func(ctx context.Context, params zones.ZoneListParams) (*pagination.V4PagePaginationArray[zones.Zone], error)) *MockAPIInterface_ListZones_Call {
	_c.Call.Return(run)
	return _c
}
