// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"strings"

	mock "github.com/stretchr/testify/mock"
)

// NewMockViper creates a new instance of MockViper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViper {
	mock := &MockViper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockViper is an autogenerated mock type for the Viper type
type MockViper struct {
	mock.Mock
}

type MockViper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViper) EXPECT() *MockViper_Expecter {
	return &MockViper_Expecter{mock: &_m.Mock}
}

// AddConfigPath provides a mock function for the type MockViper
func (_mock *MockViper) AddConfigPath(path string) {
	_mock.Called(path)
	return
}

// MockViper_AddConfigPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConfigPath'
type MockViper_AddConfigPath_Call struct {
	*mock.Call
}

// AddConfigPath is a helper method to define mock.On call
//   - path string
func (_e *MockViper_Expecter) AddConfigPath(path interface{}) *MockViper_AddConfigPath_Call {
	return &MockViper_AddConfigPath_Call{Call: _e.mock.On("AddConfigPath", path)}
}

func (_c *MockViper_AddConfigPath_Call) Run(run func(path string)) *MockViper_AddConfigPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockViper_AddConfigPath_Call) Return() *MockViper_AddConfigPath_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_AddConfigPath_Call) RunAndReturn(run func(path string)) *MockViper_AddConfigPath_Call {
	_c.Run(run)
	return _c
}

// AutomaticEnv provides a mock function for the type MockViper
func (_mock *MockViper) AutomaticEnv() {
	_mock.Called()
	return
}

// MockViper_AutomaticEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutomaticEnv'
type MockViper_AutomaticEnv_Call struct {
	*mock.Call
}

// AutomaticEnv is a helper method to define mock.On call
func (_e *MockViper_Expecter) AutomaticEnv() *MockViper_AutomaticEnv_Call {
	return &MockViper_AutomaticEnv_Call{Call: _e.mock.On("AutomaticEnv")}
}

func (_c *MockViper_AutomaticEnv_Call) Run(run func()) *MockViper_AutomaticEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_AutomaticEnv_Call) Return() *MockViper_AutomaticEnv_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_AutomaticEnv_Call) RunAndReturn(run func()) *MockViper_AutomaticEnv_Call {
	_c.Run(run)
	return _c
}

// ConfigFileUsed provides a mock function for the type MockViper
func (_mock *MockViper) ConfigFileUsed() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigFileUsed")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockViper_ConfigFileUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigFileUsed'
type MockViper_ConfigFileUsed_Call struct {
	*mock.Call
}

// ConfigFileUsed is a helper method to define mock.On call
func (_e *MockViper_Expecter) ConfigFileUsed() *MockViper_ConfigFileUsed_Call {
	return &MockViper_ConfigFileUsed_Call{Call: _e.mock.On("ConfigFileUsed")}
}

func (_c *MockViper_ConfigFileUsed_Call) Run(run func()) *MockViper_ConfigFileUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_ConfigFileUsed_Call) Return(s string) *MockViper_ConfigFileUsed_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockViper_ConfigFileUsed_Call) RunAndReturn(run func() string) *MockViper_ConfigFileUsed_Call {
	_c.Call.Return(run)
	return _c
}

// ReadInConfig provides a mock function for the type MockViper
func (_mock *MockViper) ReadInConfig() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadInConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockViper_ReadInConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadInConfig'
type MockViper_ReadInConfig_Call struct {
	*mock.Call
}

// ReadInConfig is a helper method to define mock.On call
func (_e *MockViper_Expecter) ReadInConfig() *MockViper_ReadInConfig_Call {
	return &MockViper_ReadInConfig_Call{Call: _e.mock.On("ReadInConfig")}
}

func (_c *MockViper_ReadInConfig_Call) Run(run func()) *MockViper_ReadInConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockViper_ReadInConfig_Call) Return(err error) *MockViper_ReadInConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockViper_ReadInConfig_Call) RunAndReturn(run func() error) *MockViper_ReadInConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfigFile provides a mock function for the type MockViper
func (_mock *MockViper) SetConfigFile(file string) {
	_mock.Called(file)
	return
}

// MockViper_SetConfigFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfigFile'
type MockViper_SetConfigFile_Call struct {
	*mock.Call
}

// SetConfigFile is a helper method to define mock.On call
//   - file string
func (_e *MockViper_Expecter) SetConfigFile(file interface{}) *MockViper_SetConfigFile_Call {
	return &MockViper_SetConfigFile_Call{Call: _e.mock.On("SetConfigFile", file)}
}

func (_c *MockViper_SetConfigFile_Call) Run(run func(file string)) *MockViper_SetConfigFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockViper_SetConfigFile_Call) Return() *MockViper_SetConfigFile_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetConfigFile_Call) RunAndReturn(run func(file string)) *MockViper_SetConfigFile_Call {
	_c.Run(run)
	return _c
}

// SetConfigName provides a mock function for the type MockViper
func (_mock *MockViper) SetConfigName(name string) {
	_mock.Called(name)
	return
}

// MockViper_SetConfigName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfigName'
type MockViper_SetConfigName_Call struct {
	*mock.Call
}

// SetConfigName is a helper method to define mock.On call
//   - name string
func (_e *MockViper_Expecter) SetConfigName(name interface{}) *MockViper_SetConfigName_Call {
	return &MockViper_SetConfigName_Call{Call: _e.mock.On("SetConfigName", name)}
}

func (_c *MockViper_SetConfigName_Call) Run(run func(name string)) *MockViper_SetConfigName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockViper_SetConfigName_Call) Return() *MockViper_SetConfigName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetConfigName_Call) RunAndReturn(run func(name string)) *MockViper_SetConfigName_Call {
	_c.Run(run)
	return _c
}

// SetConfigType provides a mock function for the type MockViper
func (_mock *MockViper) SetConfigType(typ string) {
	_mock.Called(typ)
	return
}

// MockViper_SetConfigType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfigType'
type MockViper_SetConfigType_Call struct {
	*mock.Call
}

// SetConfigType is a helper method to define mock.On call
//   - typ string
func (_e *MockViper_Expecter) SetConfigType(typ interface{}) *MockViper_SetConfigType_Call {
	return &MockViper_SetConfigType_Call{Call: _e.mock.On("SetConfigType", typ)}
}

func (_c *MockViper_SetConfigType_Call) Run(run func(typ string)) *MockViper_SetConfigType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockViper_SetConfigType_Call) Return() *MockViper_SetConfigType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetConfigType_Call) RunAndReturn(run func(typ string)) *MockViper_SetConfigType_Call {
	_c.Run(run)
	return _c
}

// SetDefault provides a mock function for the type MockViper
func (_mock *MockViper) SetDefault(key string, value any) {
	_mock.Called(key, value)
	return
}

// MockViper_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockViper_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - key string
//   - value any
func (_e *MockViper_Expecter) SetDefault(key interface{}, value interface{}) *MockViper_SetDefault_Call {
	return &MockViper_SetDefault_Call{Call: _e.mock.On("SetDefault", key, value)}
}

func (_c *MockViper_SetDefault_Call) Run(run func(key string, value any)) *MockViper_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViper_SetDefault_Call) Return() *MockViper_SetDefault_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetDefault_Call) RunAndReturn(run func(key string, value any)) *MockViper_SetDefault_Call {
	_c.Run(run)
	return _c
}

// SetEnvKeyReplacer provides a mock function for the type MockViper
func (_mock *MockViper) SetEnvKeyReplacer(r *strings.Replacer) {
	_mock.Called(r)
	return
}

// MockViper_SetEnvKeyReplacer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvKeyReplacer'
type MockViper_SetEnvKeyReplacer_Call struct {
	*mock.Call
}

// SetEnvKeyReplacer is a helper method to define mock.On call
//   - r *strings.Replacer
func (_e *MockViper_Expecter) SetEnvKeyReplacer(r interface{}) *MockViper_SetEnvKeyReplacer_Call {
	return &MockViper_SetEnvKeyReplacer_Call{Call: _e.mock.On("SetEnvKeyReplacer", r)}
}

func (_c *MockViper_SetEnvKeyReplacer_Call) Run(run func(r *strings.Replacer)) *MockViper_SetEnvKeyReplacer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *strings.Replacer
		if args[0] != nil {
			arg0 = args[0].(*strings.Replacer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockViper_SetEnvKeyReplacer_Call) Return() *MockViper_SetEnvKeyReplacer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetEnvKeyReplacer_Call) RunAndReturn(run func(r *strings.Replacer)) *MockViper_SetEnvKeyReplacer_Call {
	_c.Run(run)
	return _c
}

// SetEnvPrefix provides a mock function for the type MockViper
func (_mock *MockViper) SetEnvPrefix(prefix string) {
	_mock.Called(prefix)
	return
}

// MockViper_SetEnvPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvPrefix'
type MockViper_SetEnvPrefix_Call struct {
	*mock.Call
}

// SetEnvPrefix is a helper method to define mock.On call
//   - prefix string
func (_e *MockViper_Expecter) SetEnvPrefix(prefix interface{}) *MockViper_SetEnvPrefix_Call {
	return &MockViper_SetEnvPrefix_Call{Call: _e.mock.On("SetEnvPrefix", prefix)}
}

func (_c *MockViper_SetEnvPrefix_Call) Run(run func(prefix string)) *MockViper_SetEnvPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockViper_SetEnvPrefix_Call) Return() *MockViper_SetEnvPrefix_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViper_SetEnvPrefix_Call) RunAndReturn(run func(prefix string)) *MockViper_SetEnvPrefix_Call {
	_c.Run(run)
	return _c
}
