name: Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - cmd/**
      - pkg/**
      - go.mod
      - go.sum
      - main.go
      - main_test.go

jobs:
  lint:
    uses: ./.github/workflows/lint-go.yaml
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
