name: Release (Production)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    needs:
      - test
      - lint

  renew-docs:
    name: Refresh pkg.go.dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull new module version
        uses: nicholas-fedor/go-proxy-pull-action@0aec5140adfe493726adba37a23a4123598dcf26
        with:
          goproxy: https://proxy.golang.org
          import_path: github.com/nicholas-fedor/gogeneratecftoken
